### PR TITLE
Change the Guide TV Poster

### PR DESCRIPTION
**Pull request by yrabl**
Change the program guide view to display the image same as displayed in USTVnow.

### CODE REVIEW

**Comment by Lunatixz** [comment]
thanks

**Comment by yrabl** [comment]
You are slow today... already added some more :-)

**Comment by Lunatixz** [comment]
maybe too fast ;)
Had to manually merge, because of conflict... 
Thanks again

**Comment by yrabl** [comment]
I've got another idea simmering

**Pull request merged**
